<?php

/**
 * MirasolWorkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MirasolWorkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MirasolWorkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MirasolWork');
    }
}