# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .actions:
    login_module:    sfGuardAuth
    login_action:    signin
    
    secure_module:   sfGuardAuth
    secure_action:   secure

  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            eaba03b5c284119e208dfccc1248bf264e000e13

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    i18n:                   true
    default_culture:        es

    standard_helpers:       [Partial, Cache, I18N, Text]
    # Enable the database manager
    use_database:           true
    enabled_modules:        [default, sfImageTransformator]